# Generated by Django 2.1.3 on 2018-11-26 04:34

from django.db import migrations

def init_categories(apps, schema_editor):
    Category = apps.get_model("moneyCount", "Category")
    defaultCategories = ["Продукты",
                         "Бензин",
                         "Телефон",
                         "Коммунальные услуги",
                         ]

    for catName in defaultCategories:
        category = Category(name=catName)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('moneyCount', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_categories),
    ]
